### ISSUE TITLE
Skin color around mouth / Ability to generalize?

### ISSUE THREAD

**Issue by danablend** [Inferencer/LipSick#11]
Hello @Inferencer.

This is a fantastic project - it's fast, and the lip movement seems to be accurate to the audio.

Right now, I'm experiencing some color mismatching in the frame box. I'm guessing it's using the rectangle landmark for each frame around the mouth or something similar? Is there a way to programmatically mask just the frame-by-frame modified part and edit only this part of the source video (eg mouth + chin + lower face)?

Guessing color mismatching could have something to do with the training of the current model not having seen enough to generalize? Interested in hearing any thoughts. I know for LipSync3D, they built a lighting normalization mechanism to make it work in any lighting with less dependency on the model's ability to learn to render the frame with lighting (https://www.youtube.com/watch?v=L1StbX9OznY). Perhaps this may be something useful we could leverage?

I might be able to have compute to help improving some of the models in the near future - where would this be the most useful?

I just pulled from main and started the gradio server, then uploaded video/audio and pressed the button. Here's an example I've produced:
https://github.com/Inferencer/LipSick/assets/17946756/1b721adb-6459-4448-a086-dfedeb5aed84

**Comment by Inferencer** [comment]
I will implement automatic masking if that's what one of your questions was referring too, 

Doing some more tests on color mismatching to find the best solution and the main cause while avoiding further training,

I know the reason your mouth in the test is blurry and I can fix as it's to do with the teeth resolution and now I'm nearly done implementing custom ref frames we can soon upscale a single frame or 5 frames although up-scaling will come in a later update,
the color matching we get from that ref frame up-scaling is good but still not at the level of quality I want to provide to users. 

But shadows on the face I'm not too sure I will find a good solution for in the short term but we have seen an increase in video relighting papers so I am optimistic it just needs my focus to figure it out, one of the reasons I created this project apart from having to many custom files in my DINet folder was to get some community help & I think that's starting to come in even if it's not shown in the pull requests.
