### ISSUE TITLE
python app.py gives permission error in windows server

### ISSUE THREAD

**Issue by Muhammad-Awab** [Inferencer/LipSick#13]
![image](https://github.com/Inferencer/LipSick/assets/98603853/e3095ccf-ff00-45bf-bace-0d0aca86614c)

**Comment by Inferencer** [comment]
Possibly an issue with using mp3 instead of .wav (I threw together an mp3 to wav converter but didn't properly test it)
 if it's something else then it will be fixed on an update in a few hours as I am adding a new feature currently, 

let me know if using a .wav helps your current issue.

**Comment by Inferencer** [comment]
I have now updated the code, I have removed the detection of audio files that are not .wav format until I can fully confirm conversion works, they new update should also fix any errors you are getting if the issue was not audio related. Please confirm when you get a chance that this is solved.
