### ISSUE TITLE
Will the code continue to be optimized?

### ISSUE THREAD

**Issue by Jenkit-Lau** [Inferencer/LipSick#14]
The lip syncing effect is still acceptable, but the result of applying the processed frame images back onto the original face is not very good. Is it possible to continue optimizing it?

https://github.com/Inferencer/LipSick/assets/135696195/c2934a61-cb52-4a56-ade3-1a96caf16063

**Comment by Inferencer** [comment]
yes it will be optimized, you wont see those effects if you use a better source video currently but I will add an automasking feature, I just needed to get the custom reference frames & the custom crop radius done first which I have done now
