### ISSUE TITLE
Video is not being created

### ISSUE THREAD

**Issue by DerPatrice** [Inferencer/LipSick#15]
![console1](https://github.com/Inferencer/LipSick/assets/79202368/24487f9e-1e6f-43da-8de4-de2d2b261235)
![console](https://github.com/Inferencer/LipSick/assets/79202368/a264b525-472a-40bc-bbdb-986a3758f56d)

I'm getting 0 errors and everything seems to work fine but i get no video output.
Any ideas how to fix the problem?

**Comment by Inferencer** [comment]
That is strange is there a video that is playable in the ui at the end
and you have checked the Lipsick/Asserts/inference_results folder

**Comment by DerPatrice** [comment]
There is no video in the UI, and the folder is empty. The UI looks like this:
![UI](https://github.com/Inferencer/LipSick/assets/79202368/d7655582-9f3f-48dc-8dcd-f0707321fed7)

**Comment by Inferencer** [comment]
could be an ffmpeg issue
at line 225 in inference.py
`subprocess.call(cmd, shell=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)  # Suppress FFmpeg logs`
remove the line or comment it out with a # like so 
`'subprocess.call(cmd, shell=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)  # Suppress FFmpeg logs`

and save the file, I hid the ffmpeg logs so if there is an error you may not see it without removing this line.

**Comment by Inferencer** [comment]
User notified me during Discord chat they had set Gradio share to True as instructed by the Gradio help tip, I will try and suppress upgrade and public link instructions in future updates to prevent this happening in the future.
However Google Collab allows public links so they must have a different permissions setup compared to doing this locally. 

User also needed to run anaconda as administrator, user had windows 11 not sure if that's relevant but doing this fixed the issue. 
Issue is solved
