### ISSUE TITLE
Effect problem

### ISSUE THREAD

**Issue by sagg-test** [Inferencer/LipSick#16]
Hi, thanks for your great work.
The degree of mouth opening has become smaller compared to the original video. Maybe consider using few shot instead of zero shot. Will the training code be open source? Use few epochs traing to fit more corner problems?

**Comment by Inferencer** [comment]
The models are the same used in [DINet](https://github.com/MRzzm/DINet) just renamed so you can use their repo to train but based on the training issues others have encountered I think it would be a difficult task to get the results you want, 

I did mess about a few months ago with some code and the mouth did open alot more but to do this I had to increase the mouth size so it will require more experimenting, I'm sure it will just be deepspeech related so I could possibly increase certain values automatically , below is a result from the changes I tested a few months ago, I believe I set a crop_radius_1_4 the same as crop_radius or something.

https://github.com/Inferencer/LipSick/assets/121839197/6b88ec5b-717f-4198-be50-90b83b52213a

**Comment by sagg-test** [comment]
Thank you for your patient response.  Looks like the mouth did open alot .
