### ISSUE TITLE
Example of upcoming box removal feature

### ISSUE THREAD

**Issue by Inferencer** [Inferencer/LipSick#17]
Just though I would share an example of the upcoming much needed face mask/ box removal feature, bear in mind custom frames are not used on this video so the skin quality is a bit off, it runs super fast but unfortunately to achieve this effect there is tracking of the lipsynced face which is going to slow things down, we can't re-use the tracking data from the original video due to chin's moving while speaking. right now I'm just adding features but will make everything more suitable for people who are offering this tool for SaaS so data is reused etc. I assume this will be implemented next week and I will close this issue when it is

https://youtu.be/x3Ufuef1nEE

**Comment by kowalgregy** [comment]
Looks promising! Great work!

**Comment by danablend** [comment]
This is amazing!

**Comment by jakebloom** [comment]
Thanks so much - looking forward to this!

**Comment by skeletonNN** [comment]
Maybe Face Parsing can solve this bbox removal!

**Comment by Inferencer** [comment]
> Maybe Face Parsing can solve this bbox removal!

Yeah that's a good approach I will look into Real-time adaptive skin detection as that seems promising, 

I already set up landmark based alpha masking with a convex hull shape last week on my local PC then did a day of bug fixing and spent the last few days changing the file structures I keep thinking I'm nearly done but one issue solved leads to another.

It's currently setup to use the landmarks 3-15 as the shape but when it's uploaded we can play around with it. I've included a landmark map for reference.





![1592469192-74364](https://github.com/Inferencer/LipSick/assets/121839197/85269477-98ad-426c-8fe3-6090fa500aa2)

**Comment by Inferencer** [comment]
Feature added to the main branch

**Comment by univers3** [comment]
Is the code on HF updated too?

**Comment by Inferencer** [comment]
> Is the code on HF updated too?

Not yet I'm afraid, it's because some file saving paths have changed so things are saved in folders then deleted but not sure HF will allow that so might need to be changed back to gradio temp folders which means I would need to detect the paths it's being saved to.

**Comment by jitendra-koodo** [comment]
Looking forward to this..
