### ISSUE TITLE
Final video does not appear after synchronization

### ISSUE THREAD

**Issue by Annita2418** [Inferencer/LipSick#38]
Hello, after a full synchronization cycle an error appears at the end (I will paste the code below), how to solve it? Thank you

"Extracting frames from video
Hang tight! We're processing your audio, which might take a little while depending on its length.
Tracking Face
Aligning frames with driving audio
Selecting reference images based on input or randomly if unspecified
Using reference frames at indices: [49, 307, 116, 275, 264]
If each value has +5 added do not be alarmed it will -5 later
Synthesizing 314/315 frameAuto Mask stage
Extracting frames from samelength video
Extracting frames from pre_blend video
Tracking Face of Lip-synced (LipSick) video please wait..
Traceback (most recent call last):
  File "C:\Users\Work\LipSick\utils\blend.py", line 131, in <module>
    main(args.samelength_video_path, args.pre_blend_video_path)
  File "C:\Users\Work\LipSick\utils\blend.py", line 39, in main
    blend_videos(same_length_dir, pre_blend_dir, samelength_path, pre_blend_path)
  File "C:\Users\Work\LipSick\utils\blend.py", line 121, in blend_videos
    os.remove(pre_blend_path)
FileNotFoundError: [WinError 2] Unable to find the specified file: './asserts/inference_result\\pre_blend.mp4'
Complete
Result saved in ./asserts/inference_results
Thank you for using LipSick for your Lip-Sync needs."

**Comment by Inferencer** [comment]
It's not detecting ffmpeg on your system or env, I hid the logs of ffmpeg to make it cleaner that's why your not getting an error message

**Comment by Annita2418** [comment]
> It's not detecting ffmpeg on your system or env, I hid the logs of ffmpeg to make it cleaner that's why your not getting an error message

I installed ffmpeg and everything worked, thank you very much for the quick response!
