### ISSUE TITLE
改用 dlib是基于速度还是精度的考虑

### ISSUE THREAD

**Issue by tailangjun** [Inferencer/LipSick#4]
mediapipe的速度很快，可以试试，就是 frame_landmark的索引得调整。

**Comment by tailangjun** [comment]
另外我还遇到一个问题，就是推理生成的脸部会错位，不知道是 openface标注的不准确还是我的 syncnet没训练好

https://github.com/Inferencer/LipSick/assets/12316965/0ef7b127-e389-4666-b7d5-b5292a529c6c

**Comment by Inferencer** [comment]
The switch to dlib is because I needed to remove open-face, I will add more landmark trackers like media face etc as optional in the gradio UI 

The alignment issue also happens with openface depending on input video in DINet I will try and fix that

**Comment by Inferencer** [comment]
> 另外我还遇到一个问题，就是推理生成的脸部会错位，不知道是 openface标注的不准确还是我的 syncnet没训练好
> CCTV0002_facial_dubbing_add_audio.mp4

This video was created by DINet it looks like, have your tried using a different video size like 1920x1080 ?
I have seen alignment issues before but not like that.

**Comment by tailangjun** [comment]
懂了，非常感谢
