### ISSUE TITLE
Hugging face space Client error '403 Forbidden' for url

### ISSUE THREAD

**Issue by bryancheny** [Inferencer/LipSick#5]
I tried cloning the hugging face space and calling it with python gradient client, but always get the error 403 forbidden url '
https://[username]-lipsick.hf.space/file=/home/user/app/asserts/inference_result/assets2FmanTalking_LIPSICK.mp4' 
This is my code. I'm using a write key. When I swap the model out for other models, it can run successfully, but I just can't get this model to work. Anyone else facing the same issue?

from dotenv import load_dotenv
from gradio_client import Client, file

HF_TOKEN = os.getenv("HF_TOKEN")
client = Client("[username]/LipSick", hf_token=HF_TOKEN)
result = client.predict(
    source_video=file(source_video_path),  
    driving_audio=file(source_audio_path),
    api_name="/predict",
)

**Comment by Inferencer** [comment]
Not my area.. I'm assuming you have duplicated the space and trying to use the API, the only thing I can suggest is to ensure the URL is correct, I unfortunately capitalized a lot of stuff and used lower case too which is pretty inconsistent and i see in your URL the name LipSick is all lowercase, could be something else but haven't learned API's yet.

**Comment by bryancheny** [comment]
Thanks! I think it's an issue with gradio client, so i'll try using docker instead.
