### ISSUE TITLE
What can i solve the face box?

### ISSUE THREAD

**Issue by skeletonNN** [Inferencer/LipSick#8]
Great Job! When i infer the video, it can be found that there is a box for face. Can you solve it? Thank you!
<img width="526" alt="image" src="https://github.com/Inferencer/LipSick/assets/77391149/e848f5e8-c193-4d0d-a729-5a4ad65f6cb9">

**Comment by Inferencer** [comment]
I can solve it, working on something that stops the box jittering first this will help when I code the box removal.
For a quick fix while I'm working on it you can manually mask using a video editing tool 

(note: It's good to watch the first few mins of the davinci tut even if you don't have it as it will explain difference in length between the input & output although I will later automate that)

[Davinci Tut](https://streamable.com/rme7wf)
or
[After Effects Tut](https://youtu.be/e9uXlOuLvCk?si=eqoKgu22fouWKWqH)

**Comment by skeletonNN** [comment]
Can I use the python code?

---- Replied Message ----
| From | ***@***.***> |
| Date | 05/08/2024 01:16 |
| To | Inferencer/LipSick ***@***.***> |
| Cc | skeleton ***@***.***>,
Author ***@***.***> |
| Subject | Re: [Inferencer/LipSick] What can i solve the face box? (Issue #8) |

I can solve it, working on something that stops the box jittering first this will help when I code the box removal.
For a quick fix while I'm working on it you can manually mask using a video editing tool

(note: It's good to watch the first few mins of the davinci tut even if you don't have it as it will explain difference in length between the input & output although I will later automate that)

Davinci Tut
or
After Effects Tut

**Comment by Inferencer** [comment]
when it's working I'll upload it, could be end of this week or it could be end of next week

**Comment by skeletonNN** [comment]
Thank You!

**Comment by skeletonNN** [comment]
One more thing! I find the color is different from the original pic!
<img width="407" alt="image" src="https://github.com/Inferencer/LipSick/assets/77391149/ee39dfe7-4d6d-4af7-bd76-caa57f0efcf0">
I think the problem is due to the Ditnet. Can you some suggestions?

**Comment by Inferencer** [comment]
I always assumed this was due to the pre-trained model being trained on low quality dark lighting datasets but I guess it could be possible to attempt to match the lighting which could affect the color I will certainly do some experiments to find out

**Comment by Inferencer** [comment]
https://github.com/Inferencer/LipSick/assets/121839197/bc089436-dcaa-46eb-88ec-c9a84bd64fb0

The custom crop radius has now been uploaded in the windows/ main branch so after you calculate the crop_radius in the crop radius tab and set the recommended value in the main tab you will get less box flickering so that's stage one done which will help with box removal.

I need to make this more user friendly though

**Comment by skeletonNN** [comment]
> I always assumed this was due to the pre-trained model being trained on low quality dark lighting datasets but I guess it could be possible to attempt to match the lighting which could affect the color I will certainly do some experiments to find out

I understand it should conform to the lighting color information in the reference image, but it seems that this information has not been learned.

**Comment by Inferencer** [comment]
> > I always assumed this was due to the pre-trained model being trained on low quality dark lighting datasets but I guess it could be possible to attempt to match the lighting which could affect the color I will certainly do some experiments to find out
> 
> I understand it should conform to the lighting color information in the reference image, but it seems that this information has not been learned.

Another theory is as its currently using 5 reference frames.. (I will change that soon to use an optional single frame up to 5 frames) 
the frames are being layered on top of each-other at the learning stage which is decreasing quality, I have found when using a single frame although the lip-sync is less slightly expressive that teeth & skin quality increase dramatically

**Comment by skeletonNN** [comment]
> > > I always assumed this was due to the pre-trained model being trained on low quality dark lighting datasets but I guess it could be possible to attempt to match the lighting which could affect the color I will certainly do some experiments to find out
> > 
> > 
> > I understand it should conform to the lighting color information in the reference image, but it seems that this information has not been learned.
> 
> Another theory is as its currently using 5 reference frames.. (I will change that soon to use an optional single frame up to 5 frames) the frames are being layered on top of each-other at the learning stage which is decreasing quality, I have found when using a single frame as reference although the lip-sync is less slightly expressive that teeth & skin quality increase dramatically this could possibly be affecting color too.
> 
> This is an example of bad skin and teeth then after there is an example of using a single reference frame for all frames, although the target was doing weird chin movements in both videos I was more focused on the teeth at the time
> 
>  BadSkin.mp4 
>  Teeth.mp4 
> As you can see the skin color matching improves, for clarification this was a single reference frame and the reference frame was up-scaled with GFPGAN so my current theory is its using too many reference frames and also teeth related, based on past experiments when the teeth are dim so is the skin, the worse quality the teeth the worse quality & color the skin.

Excellent conclusion, I will try it.

**Comment by skeletonNN** [comment]
In some cases, I use silent audio to get them to shut up and the mouth can close completely. But the generated frame video is constantly shaking due to the presence of the frame.

https://github.com/Inferencer/LipSick/assets/77391149/02e5ccb6-528f-4a94-8052-b179e4dc2037

**Comment by Inferencer** [comment]
I created a decent detector for the best crop radius but just found that the new crop radius is not correctly implemented into the code so it's defaulting to the normal shaking regardless of crop radius, will fix soon to prevent shaking.
